name = "nocapswimtw"
pages_build_output_dir = "./dist"
compatibility_date = "2026-09-17"

[vars]
ENVIRONMENT = "production"

[[d1_databases]]
binding = "DB"
database_name = "nocapswimtw"
database_id = "05987cd1-b000-4ebb-82c4-cdd210926681"



